name = "storage-workers"
type = "webpack"

account_id = "fab68c77d8655d69dcdd2d0eefd55a8a"
workers_dev = true
compatibility_date = "2021-09-23"

kv_namespaces = [
    { binding = "PINS", preview_id = "f246bccdb3a84e72ab3d80a72f897ef3", id = "430a48a4a2ae4c67a6025551f0978787" }
]

[env.production]
# The ID of the domain to deploying to
zone_id = "14c2aa3ca6d98bddd3b8032d11bba3e5"

# The route pattern your Workers application will be served at
route = "storage.geoweb.network/*"